<a href="https://colab.research.google.com/github/K4m1-5am4/DataAnalysis_and_ML/blob/main/TorchLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import torch
torch.__version__

'2.8.0+cu126'

In [36]:
k=torch.rand(10)*100
print(k.argmax())
print(k.dtype)
pl = k.type(torch.float16)
print(pl)

tensor(4)
torch.float32
tensor([78.5000, 54.1875, 74.1875, 78.3750, 89.1875, 31.3906, 23.9844, 46.8125,
        59.3750, 58.2500], dtype=torch.float16)


In [46]:
apt=torch.arange(1.,7.)
apt_s=torch.stack([apt,apt,apt,apt,apt], dim=0)
print(apt_s);print(apt_s.shape)

tensor([[1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.]])
torch.Size([5, 6])


In [51]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
import numpy as np

In [61]:
pot=np.arange(1,10,1)

In [63]:
keke=torch.from_numpy(pot)
keke

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
kk=torch.Tensor.numpy(x)

In [67]:
kk

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B