In [ ]:
import torch
torch.__version__

'2.8.0+cu126'

In [ ]:
scaler = torch.tensor([[[6,6],[4,6],[2,8]]])
print(scaler)

tensor([[[6, 6],
         [4, 6],
         [2, 8]]])


In [ ]:
tri = torch.rand(size=(2,2))
tri

tensor([[0.5206, 0.3371],
        [0.4137, 0.3386]])

In [ ]:
a=torch.ones(5,4)

In [ ]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
torch.zeros_like(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])